"""Public reader API for fabulexa_forge."""

from __future__ import annotations

from fabulexa_forge.reader.conformance import (
    CheckResult,
    ConformanceReport,
    run_check,
    validate,
)
from fabulexa_forge.reader.emit import Emit, open_emit, pin_session_timezone
from fabulexa_forge.reader.errors import (
    ColumnNotFoundError,
    EmitNotFoundError,
    PresentationKeysInvalidError,
    ReaderError,
    RunDatabaseError,
    SidecarParseError,
    SidecarStructureError,
    TableNotFoundError,
    TemporalClassUnavailableError,
    UnsupportedBaseFormatVersionError,
)
from fabulexa_forge.reader.records_columns import (
    REF_INDEX_PREFIX,
    RecordsColumnRole,
    StructuralInstant,
    records_column_role,
    records_structural_column_is_mutable,
    ref_index_sibling,
    structural_instant_columns,
)
from fabulexa_forge.reader.relations import (
    build_history_relation_sql,
    build_membership_relation_sql,
    build_records_relation_sql,
    distinct_prop_values,
)
from fabulexa_forge.reader.sidecar import (
    BranchCensus,
    BranchEntry,
    ColumnSpec,
    KeySpace,
    PartitionKey,
    PresentationKeys,
    RecordRoles,
    RuntimeAnchor,
    SeriesCensus,
    Sidecar,
    SubTypeColumns,
    TableSpec,
    TemporalClass,
    WholeColumnClaim,
    combined_claim,
    union_safe,
)

__all__ = [
    "BranchCensus",
    "BranchEntry",
    "CheckResult",
    "ColumnNotFoundError",
    "ColumnSpec",
    "ConformanceReport",
    "Emit",
    "EmitNotFoundError",
    "KeySpace",
    "PartitionKey",
    "PresentationKeys",
    "PresentationKeysInvalidError",
    "ReaderError",
    "REF_INDEX_PREFIX",
    "RecordRoles",
    "RecordsColumnRole",
    "RunDatabaseError",
    "RuntimeAnchor",
    "SeriesCensus",
    "Sidecar",
    "SidecarParseError",
    "SidecarStructureError",
    "StructuralInstant",
    "SubTypeColumns",
    "TableNotFoundError",
    "TableSpec",
    "TemporalClass",
    "TemporalClassUnavailableError",
    "UnsupportedBaseFormatVersionError",
    "WholeColumnClaim",
    "build_history_relation_sql",
    "build_membership_relation_sql",
    "build_records_relation_sql",
    "combined_claim",
    "distinct_prop_values",
    "open_emit",
    "pin_session_timezone",
    "records_column_role",
    "records_structural_column_is_mutable",
    "ref_index_sibling",
    "run_check",
    "structural_instant_columns",
    "union_safe",
    "validate",
]
