"""Companion README renderer: mode template x overlay x derived facts.

Renders the ordering contract (`docs/architecture/companion-artifacts.md`
§ The README): title + generated-artifact marker naming the manifest ->
overlay overview (when present) -> the mode template's semantics prose ->
one section per output table (overlay note, derived column inventory, row
count) -> resolved anchor facts -> emit identity.
"""

from __future__ import annotations

import importlib.resources
from pathlib import Path
from typing import TYPE_CHECKING, Literal

from fabulexa_forge.exporters.companion.manifest import build_emit_identity

if TYPE_CHECKING:
    from fabulexa_forge.anchor import EffectiveAnchor
    from fabulexa_forge.exporters.companion.manifest import EmitIdentity
    from fabulexa_forge.exporters.companion.overlay import ReadmeOverlay
    from fabulexa_forge.exporters.query_spec import ExportReport, TableKeys, TableReport
    from fabulexa_forge.reader.emit import Emit

_MODE_TITLES: dict[str, str] = {
    "dimensional": "Dimensional",
    "source": "Source",
    "base": "Base",
}


def _load_mode_template(mode: Literal["dimensional", "source", "base"]) -> str:
    """Load one packaged mode template's prose.

    Tries `importlib.resources` (the wheel / non-editable install layout)
    first, then a `__file__`-relative in-tree fallback — the same two-path
    resolution `reader/_schema.py` uses for the vendored contract.

    Args:
        mode: The export mode naming the template file (`<mode>.md`).

    Returns:
        The template's raw markdown text.

    Raises:
        FileNotFoundError: The packaged template is missing via both
            resolution paths — a packaging defect.
    """
    resource = importlib.resources.files("fabulexa_forge.exporters.companion") / (
        f"templates/{mode}.md"
    )
    try:
        return resource.read_text(encoding="utf-8")
    except (FileNotFoundError, TypeError):
        pass

    fallback = Path(__file__).parent / "templates" / f"{mode}.md"
    if not fallback.exists():
        raise FileNotFoundError(
            f"packaged README template not found via importlib.resources or "
            f"fallback path {fallback}. This is a packaging defect."
        )
    return fallback.read_text(encoding="utf-8")


def _render_title(
    mode: Literal["dimensional", "source", "base"], manifest_filename: str
) -> str:
    """The README's title + generated-artifact marker."""
    return (
        f"# {_MODE_TITLES[mode]} Export\n\n"
        "Generated by fabulexa-forge; do not edit by hand. See "
        f"`{manifest_filename}` for this export's machine-readable companion "
        "manifest."
    )


def _mark_column(name: str, keys: "TableKeys | None") -> str:
    """The key-marking suffix for one column, or "" when it declares none."""
    if keys is None:
        return ""
    if name in keys.primary_key:
        return " [primary key]"
    if any(name in unique_columns for unique_columns in keys.unique):
        return " [unique]"
    return ""


def _render_table_section(table: "TableReport", overlay: "ReadmeOverlay | None") -> str:
    """One output table's section: overlay note, column inventory, row count."""
    lines = [f"### {table.name}"]
    note = None if overlay is None else overlay.table_notes.get(table.name)
    if note:
        lines.append(note)
    columns = "\n".join(
        f"- `{name}` ({type_text}){_mark_column(name, table.keys)}"
        for name, type_text in table.columns
    )
    lines.append(f"Columns:\n\n{columns}")
    if table.row_count is not None:
        lines.append(f"Row count: {table.row_count}")
    return "\n\n".join(lines)


def _render_anchor_section(anchor: "EffectiveAnchor | None") -> str:
    """The resolved anchor facts, present and absent renderings both covered."""
    if anchor is None:
        return (
            "## Anchor\n\n"
            "No wallclock anchor was resolved for this export; sim-time "
            "columns render as raw integers."
        )
    return (
        "## Anchor\n\n"
        f"- Start instant: {anchor.start_instant.isoformat()}\n"
        f"- Timezone: {anchor.timezone!s}"
    )


def _render_emit_identity_section(identity: "EmitIdentity") -> str:
    """The emit-identity facts section, from the manifest's `emit` block."""
    runtime = identity.runtime
    runtime_line = (
        "none declared"
        if runtime is None
        else f"timezone={runtime.timezone}, start_datetime={runtime.start_datetime}"
    )
    return (
        "## Emit Identity\n\n"
        f"- base_format_version: {identity.base_format_version}\n"
        f"- base.json SHA-256: {identity.sidecar_sha256}\n"
        f"- fork_path: {identity.fork_path}\n"
        f"- slice_at: {identity.slice_at}\n"
        f"- runtime: {runtime_line}"
    )


def render_readme(
    mode: Literal["dimensional", "source", "base"],
    emit: "Emit",
    report: "ExportReport",
    overlay: "ReadmeOverlay | None",
    anchor: "EffectiveAnchor | None",
    manifest_filename: str,
) -> str:
    """Render the README's full ordering contract for one export invocation.

    Args:
        mode: The export mode, selecting the packaged template.
        emit: The open emit (for the emit-identity section).
        report: The invocation's per-table report.
        overlay: The parsed overlay, or None.
        anchor: The resolved effective anchor, or None.
        manifest_filename: The sibling manifest file's basename, named in
            the title's generated-artifact marker.

    Returns:
        The complete README text, ending in a single trailing newline.
    """
    sections = [_render_title(mode, manifest_filename)]
    if overlay is not None and overlay.overview:
        sections.append(f"## Overview\n\n{overlay.overview}")
    sections.append(_load_mode_template(mode).strip())
    sections.extend(_render_table_section(table, overlay) for table in report.tables)
    sections.append(_render_anchor_section(anchor))
    sections.append(_render_emit_identity_section(build_emit_identity(emit)))
    return "\n\n".join(sections) + "\n"
